---
deployment:
  tasks:
    - export DEPLOYPATH=/home/useradmin/api.mosaicandtiledepot.com/
    - /usr/local/cpanel/3rdparty/bin/git checkout --theirs .
    - /bin/cp main/.env.example main/.env

    -  /bin/php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    -  /bin/php -r "if (hash_file('sha384', 'composer-setup.php') === 'e5325b19b381bfd88ce90a5ddb7823406b2a38cff6bb704b0acc289a09c8128d4a8ce2bbafcd1fcbdc38666422fe2806') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    -  /bin/php composer-setup.php
    -  /bin/php -r "unlink('composer-setup.php');"
    -  /bin/mv composer.phar /usr/local/bin/composer

    - /usr/local/cpanel/3rdparty/bin/git config --global user.email "mdgrisalez@misena.edu.co"
    - /usr/local/cpanel/3rdparty/bin/git config --global user.name "angell007" .
    - /usr/local/cpanel/3rdparty/bin/git config --global user.password "Angell00-7" .
    - /usr/local/cpanel/3rdparty/bin/git add .
    - "echo 'Pre up files...'"
    # - /usr/local/cpanel/3rdparty/bin/git commit -m "changes in pro"
metadata:
    name: "App Qr"
    version: "1.0"
    author: "Danilo Grisalez"
post_deploy:
pre_deploy:
    - "echo 'Pre up files...'"
hooks:
  pre:
    - command: "echo 'Backing up files...'"
  post:
    - command: "echo 'Deployment complete.'"